# Generated by Django 5.2 on 2025-04-14 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Awastha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nakshatra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lord', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rashi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lord', models.CharField(max_length=20)),
                ('element', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserKundali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('D1', 'Lagna Chart'), ('D9', 'Navamsa Chart')], max_length=5)),
                ('ascendant_lord', models.CharField(max_length=20)),
                ('varna', models.CharField(max_length=50)),
                ('vashya', models.CharField(max_length=50)),
                ('yoni', models.CharField(max_length=50)),
                ('gan', models.CharField(max_length=50)),
                ('nadi', models.CharField(max_length=50)),
                ('charan', models.IntegerField()),
                ('yog', models.CharField(max_length=50)),
                ('karan', models.CharField(max_length=50)),
                ('tithi', models.CharField(max_length=50)),
                ('yunja', models.CharField(max_length=50)),
                ('tatva', models.CharField(max_length=50)),
                ('name_alphabet', models.CharField(max_length=5)),
                ('paya', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ascendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ascendants', to='kundali.rashi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kundali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundali.userkundali')),
            ],
        ),
        migrations.CreateModel(
            name='PlanetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_degree', models.FloatField()),
                ('norm_degree', models.FloatField()),
                ('speed', models.FloatField()),
                ('is_retro', models.BooleanField()),
                ('nakshatra_pad', models.IntegerField()),
                ('is_planet_set', models.BooleanField()),
                ('awastha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundali.awastha')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundali.house')),
                ('nakshatra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundali.nakshatra')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundali.planet')),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundali.rashi')),
                ('kundali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet_positions', to='kundali.userkundali')),
            ],
        ),
    ]
