# Generated by Django 5.2 on 2025-04-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kundali', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='nakshatra',
            name='alias',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planet',
            name='alias',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='planet',
            name='is_benefic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planet',
            name='is_dasa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planet',
            name='is_dhanayog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planet',
            name='is_inner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='is_karaka',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planet',
            name='is_lagna',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planet',
            name='is_malefic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planet',
            name='is_rajayog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planet',
            name='is_shadow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planet',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rashi',
            name='alias',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='nakshatra',
            name='lord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundali.planet'),
        ),
        migrations.AlterField(
            model_name='rashi',
            name='lord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundali.planet'),
        ),
        migrations.AlterField(
            model_name='rashi',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundali.element'),
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundali.language')),
            ],
        ),
    ]
