# Generated by Django 5.2 on 2025-04-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kundali', '0002_element_language_nakshatra_alias_planet_alias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='nakshatra',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='rashi',
            name='alias',
        ),
    ]
